
import { DisplaySettings } from '@/types/displaySettings';

export const getDefaultSettings = (bakery_id: string): Omit<DisplaySettings, 'id'> => ({
  bakery_id,
  background_type: 'gradient' as const,
  background_color: '#ffffff',
  background_gradient_start: '#f3f4f6',
  background_gradient_end: '#e5e7eb',
  background_image_url: undefined,
  header_font_size: 32,
  body_font_size: 16,
  text_color: '#111827',
  header_text_color: '#111827',
  card_background_color: '#ffffff',
  card_border_color: '#e5e7eb',
  card_shadow_intensity: 3,
  border_radius: 8,
  spacing: 16,
  product_card_color: '#ffffff',
  product_text_color: '#374151',
  product_accent_color: '#3b82f6',
  product_card_size: 100,
  product_1_bg_color: '#ffffff',
  product_2_bg_color: '#f9fafb',
  product_3_bg_color: '#f3f4f6',
  product_1_text_color: '#1f2937',
  product_2_text_color: '#1f2937',
  product_3_text_color: '#1f2937',
  product_1_accent_color: '#3b82f6',
  product_2_accent_color: '#10b981',
  product_3_accent_color: '#f59e0b',
  progress_bar_color: '#3b82f6',
  progress_background_color: '#e5e7eb',
  progress_height: 8,
  show_progress_percentage: true,
  show_progress_bar: true,
  auto_refresh_interval: 30,
  show_truck_icon: false,
  truck_icon_size: 48,
  show_status_indicator: true,
  status_indicator_font_size: 32,
  status_indicator_padding: 24,
  status_in_progress_color: '#3b82f6',
  status_completed_color: '#10b981',
  status_pending_color: '#f59e0b',
  status_delivered_color: '#059669',
  show_customer_info: true,
  show_order_numbers: true,
  show_delivery_dates: true,
  show_product_images: false,
  enable_animations: true,
  animation_speed: 'normal' as const,
  fade_transitions: true,
  progress_animation: true,
  always_show_customer_name: true,
  packing_status_ongoing_color: '#3b82f6',
  packing_status_completed_color: '#10b981',
  // Shared display settings defaults
  show_stats_cards: true,
  stats_columns: 3,
  stats_icon_color: '#3b82f6',
  stats_card_height: 'normal' as const,
  customer_cards_columns: 3,
  customer_card_height: 'normal' as const,
  show_customer_numbers: true,
  show_status_badges: true,
  customer_cards_gap: 24,
  main_title: 'Felles Display',
  subtitle: 'Pakkestatus for kunder',
  show_date_indicator: true,
  max_products_per_card: 10,
  product_list_style: 'normal' as const,
  show_line_items_count: true,
  customer_sort_order: 'alphabetical' as const,
  // Screen size and layout optimization
  screen_size_preset: 'standard' as const,
  force_single_screen: false,
  large_screen_optimization: false,
  // Basket quantity display settings
  show_basket_quantity: false,
  basket_display_format: 'total_first' as const,
  // Enhanced shared display settings
  hide_empty_customers: false,
  show_delivery_date_indicators: true,
  auto_hide_completed_customers: false,
  auto_hide_completed_timer: 30,
  customer_priority_mode: 'none' as const,
  // Typography settings
  font_family: 'Inter',
  line_height: 1.5,
  text_shadow_enabled: false,
  text_shadow_color: '#00000020',
  text_shadow_blur: 2,
  text_shadow_offset_x: 1,
  text_shadow_offset_y: 1,
  // Layout and responsiveness settings
  auto_screen_detection: true,
  fullscreen_mode: false,
  minimum_card_width: 200,
  display_padding: 16,
  display_margin: 8,
  responsive_breakpoint: 'medium' as const,
  // Interactivity settings
  touch_friendly_sizes: false,
  touch_target_size: 44,
  pause_mode_enabled: false,
  show_manual_refresh_button: false,
  manual_refresh_button_position: 'top-right' as const,
});
