
import { DisplaySettings } from '@/types/displaySettings';

export const getDefaultSettings = (bakery_id: string): Omit<DisplaySettings, 'id'> => ({
  bakery_id,
  background_type: 'gradient' as const,
  background_color: '#ffffff',
  background_gradient_start: '#f3f4f6',
  background_gradient_end: '#e5e7eb',
  background_image_url: undefined,
  header_font_size: 32,
  body_font_size: 16,
  text_color: '#111827',
  header_text_color: '#111827',
  card_background_color: '#ffffff',
  card_border_color: '#e5e7eb',
  card_shadow_intensity: 3,
  border_radius: 8,
  spacing: 16,
  product_card_color: '#ffffff',
  product_text_color: '#374151',
  product_accent_color: '#3b82f6',
  product_card_size: 100,
  product_1_bg_color: '#ffffff',
  product_2_bg_color: '#f9fafb',
  product_3_bg_color: '#f3f4f6',
  product_1_text_color: '#1f2937',
  product_2_text_color: '#1f2937',
  product_3_text_color: '#1f2937',
  product_1_accent_color: '#3b82f6',
  product_2_accent_color: '#10b981',
  product_3_accent_color: '#f59e0b',
  progress_bar_color: '#3b82f6',
  progress_background_color: '#e5e7eb',
  progress_height: 8,
  show_progress_percentage: true,
  show_progress_bar: true,
  auto_refresh_interval: 30,
  show_truck_icon: false,
  truck_icon_size: 48,
  show_status_indicator: true,
  status_indicator_font_size: 32,
  status_indicator_padding: 24,
  status_in_progress_color: '#3b82f6',
  status_completed_color: '#10b981',
  status_pending_color: '#f59e0b',
  status_delivered_color: '#059669',
  show_customer_info: true,
  show_order_numbers: true,
  show_delivery_dates: true,
  show_product_images: false,
  enable_animations: true,
  animation_speed: 'normal' as const,
  fade_transitions: true,
  progress_animation: true,
  always_show_customer_name: true,
  packing_status_ongoing_color: '#3b82f6',
  packing_status_completed_color: '#10b981',
  // Cat animation defaults matching database defaults
  enable_cat_animations: false,
  cat_animation_speed: 'normal' as const,
  show_bouncing_cats: true,
  show_falling_cats: true,
  show_running_cats: true,
});
